# syntax=docker/dockerfile:1

FROM golang:1.24-alpine3.22 AS base
#
# To accelerate the build process, you may uncomment this section.
# RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories
#
RUN apk add --no-cache make bash clang15 g++ libbpf-dev curl git \
	musl-dev capnproto-dev binutils-gold python3 python3-dev py3-pip \
	py3-setuptools py3-wheel py3-pkgconfig cython pkgconf lz4-dev \
	libunwind-dev elfutils-dev # for golangci-lint, capnp compile, memray bundle

ENV GOPATH="/go"
ENV GOROOT="/usr/local/go"
ENV GOPROXY="https://goproxy.cn,https://goproxy.io,direct"
ENV PATH="${GOPATH}/bin:${GOROOT}/bin:/usr/lib/llvm15/bin:${PATH}"

# For golang 1.23.0
# gofumpt@v0.8.0, https://github.com/mvdan/gofumpt/blob/master/CHANGELOG.md
# goimports@v0.36.0
# golangci-lint https://github.com/golangci/golangci-lint/blob/main/CHANGELOG-v1.md
RUN set -x; \
    go install mvdan.cc/gofumpt@v0.8.0 && \
    go install mvdan.cc/sh/v3/cmd/shfmt@v3.11.0 && \
    go install golang.org/x/tools/cmd/goimports@v0.36.0 && \
    go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.62.2 && \
    go install github.com/vektra/mockery/v2@v2.53.6 && \
    go install capnproto.org/go/capnp/v3/capnpc-go@latest

FROM base AS dev-build
WORKDIR /go/huatuo-bamai
ENV GOCACHE=/root/.cache/go-build
COPY . .
RUN --mount=type=cache,target=${GOCACHE} \
    make all && \
    cp -a _output /tmp/huatuo-bamai

FROM alpine:3.22.0 AS dev-runtime
ARG RUN_PATH=/home/huatuo-bamai
RUN apk add --no-cache curl
COPY --from=dev-build /tmp/huatuo-bamai ${RUN_PATH}
WORKDIR ${RUN_PATH}

# Keep the default target as the interactive development toolchain image.
FROM base AS devel
